<?php
/**
 * @file fp.module
 * Contains the Furness Partnership custom modules.
 */

/**
 * Implements hook_field_attach_validate()
 *
 */
function fp_field_attach_validate($entity_type, $entity, &$errors) {
  $valid = true;
  foreach($entity->field_image['und'] as $key => $item) {
    if($entity->field_image['und'][$key]['fid'] > 0) {
      if($entity->field_image['und'][$key]['alt'] == '') {
        $valid = false;
        break;
      }
    }
  }
  if(!$valid) {
    $errors['field_image']['und'][0]['alt'] = array(
      'error' => 'field_alt_invalid',
      'message' => t('Alternate text field(s) is required.'),
    );
  }
}
